### ISSUE TITLE
Client improvement ideas

### ISSUE THREAD

**Issue by VeikkoLehmuskorpi** [doughtnerd/BeatHub#3]
Here are some improvement ideas I came up with after switching to use this as my primary client while playing in VR.

- Automatic search after a debounce time
- Search filters
- Tooltips
    - explain the meaning some icons, like the sidebar icons or the small beatmap stat icons
- Clearer distinction between each beatmap in a list
    - e.g. differing constrast in the background, larger padding or a faint line separating the beatmaps
- Better text legibility
    - bigger font especially for the beatmap stat lines
    - WCAG 2.0 compliant colors and size
- Toasts
    - e.g. when a download is complete
- Changing the state of the download button
    - active/disabled based on the download state
- VR friendly CSS toggle
    - Even larger icons and fonts
- Volume slider
- Time filtering on each tab
    - e.g. show only the most downloaded songs in the past month, or past two months, etc.

Of course, some of them are just my opinions and they don't all have to be implemented! But if you do agree with them and need help, I would be willing to at least give it a try when I have some time.

**Comment by doughtnerd** [comment]
Search debounce implemented in PR #5 
Tooltips implemented in PR #4
Clearer distinctions, app legibility, WCAG updates, toasts, and other app readability things implemented (and currently ongoing) in AppLegibility branch

Anything that increases search functionality is dependent on the BeatSaver.com api and Lucene search syntax but I've wanted this as well and am currently investigating what can be done.

Other points raised here would need more elaboration on what exactly you mean. Such as:
download states, VR UI needs, etc.

Once some app legibility things are done, I'll be creating a new release. If you have version 1.1.1, you should receive the update automatically

**Comment by VeikkoLehmuskorpi** [comment]
Thank you, great improvements already!

> Other points raised here would need more elaboration on what exactly you mean. Such as:
> download states, VR UI needs, etc.

Even though downloading a beatmap can be very quick, for a better user experience, I think the loading icon state should be a bit longer, on par with the song preview button. Of course, if the loading takes longer, there's no need to artificially delay the action. Only if the download is near instantaneous should there be a small delay.

After the download has been completed and the user has been informed of it with a toast, maybe the download button could be completely disabled (but not hidden) or changed into a delete button. 

Volume slider is self explanatory, perhaps next to the mute/unmute button or above when hovered above said button.

A separate VR UI might not be necessary after the legibility changes, but ideally everything (aside from the sidebar) would be ~2 times larger. When I'm playing BeatSaber and use the SteamVR desktop view to download songs, it's quite hard to see the song names or the details of the cover. Beatmap stats are way too small right now, but I see you're already making some changes in that regard.

**Comment by doughtnerd** [comment]
Thanks for the feedback! I'll see what I can do to get those improvements in. I'll close this issue and open up some separate ones for the feature requests you've made for easier tracking.
